export const STORE_PERSONAL_INFO = 'STORE_PERSONAL_INFO';
export const STORE_SYMPTOMS = 'STORE_SYMPTOMS';
export const STORE_MEDICAL_INFO = 'STORE_MEDICAL_INFO';
export const STORE_TRAVEL_HISTORY = 'STORE_TRAVEL_HISTORY';
export const STORE_GENERAL_QUESTIONS = 'STORE_GENERAL_QUESTIONS';
export const CREATE_REPORT = 'CREATE_REPORT';
export const SET_APP_STATE = 'SET_APP_STATE';
export const STORE_USER = 'STORE_USER';