export const REPORT_CREATION_LOADING = 'REPORT_CREATION_LOADING';
export const SHOW_REPORT_CREATION_SUCCESS = 'SHOW_REPORT_REPORT_CREATION_SUCCESS';
export const SHOW_REPORT_CREATION_FAILURE = 'SHOW_REPORT_REPORT_CREATION_FAILURE';