export interface Report{

}

export interface CityReport{
  city: string;
  reports: Report[]
}

export interface ReportsState{
  data: Report[];
  error: string;
  loading: boolean;
}

export interface ReportState{
  data: Report | null;
  error: string;
  loading: boolean;
}

export enum ReportActionTypes{
  GET_REPORT_REQUEST = 'GET_REPORT_REQUEST',
  GET_REPORT_REQUEST_SUCCESS = 'GET_REPORT_REQUEST_SUCCESS',
  GET_REPORT_REQUEST_FAILURE = 'GET_REPORT_REQUEST_FAILURE',

  GET_REPORTS_BY_CITY_REQUEST = 'GET_REPORTS_BY_CITY_REQUEST',
  GET_REPORTS_BY_CITY_REQUEST_SUCCESS = 'GET_REPORTS_BY_CITY_REQUEST_SUCCESS',
  GET_REPORTS_BY_CITY_REQUEST_FAILURE = 'GET_REPORTS_BY_CITY_REQUEST_FAILURE',

  CREATE_REPORT_BY_CITY_REQUEST = 'CREATE_REPORT_BY_CITY_REQUEST',
  CREATE_REPORT_BY_CITY_REQUEST_SUCCESS = 'CREATE_REPORT_BY_CITY_REQUEST_SUCCESS',
  CREATE_REPORT_BY_CITY_REQUEST_FAILURE = 'CREATE_REPORT_BY_CITY_REQUEST_FAILURE',
}